name=HAS2_Wifi
version=1.0.0
author=HAS2
maintainer=HAS2
sentence=HAS2 WiFi helper library.
paragraph=Provides WiFi connection, reconnection, HTTP, and OTA helpers for HAS2 devices.
category=Communication
url=https://github.com/Fuzzyline-HAS/libraries
architectures=esp32
includes=HAS2_Wifi.h
